services:
  # Backend API Service
  - type: web
    name: ai-presentation-backend
    runtime: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements1.txt
    startCommand: python main.py
    plan: free
    healthCheckPath: /health
    
  # Frontend Streamlit Service  
  - type: web
    name: ai-presentation-frontend
    runtime: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements2.txt
    startCommand: streamlit run frontend.py --server.port $PORT --server.address 0.0.0.0
    plan: free
    


